kind: pipeline
type: docker
name: build-so-upload

steps:
  - name: setup-go
    image: golang:1.22
    commands:
      - go version
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
      - apt-get update && apt-get install -y --no-install-recommends unzip ca-certificates curl git build-essential && rm -rf /var/lib/apt/lists/*
      - |
        if ! command -v protoc >/dev/null 2>&1; then
          PROTOC_VERSION=${PROTOC_VERSION:-24.4}
          curl -sSL -o /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          unzip -o /tmp/protoc.zip -d /usr/local >/dev/null
          rm -f /tmp/protoc.zip
        fi

  - name: gen-protos
    image: golang:1.22
    commands:
      - protoc -I=./proto --go_out=./sim/core ./proto/*.proto

  - name: build-shared-lib
    image: golang:1.22
    environment:
      CGO_ENABLED: 1
    commands:
      - go mod download
      - go build -buildmode=c-shared -o wowsimmop.so --tags=with_db ./sim/lib

  - name: upload-to-minio
    image: minio/mc
    environment:
      MINIO_ALIAS: ${MINIO_ALIAS:-minio}
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET:-artifacts}
      OUT_PATH: ${OUT_PATH:-lib/wowsimmop.so}
    commands:
      - mc alias set "$MINIO_ALIAS" "$MINIO_URL" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
      - mc mb -p "$MINIO_ALIAS/$MINIO_BUCKET" || true
      - mc cp --attr "version=${CI_COMMIT_SHA}" wowsimmop.so "$MINIO_ALIAS/$MINIO_BUCKET/$OUT_PATH-${CI_COMMIT_SHA}"
      - mc cp wowsimmop.so "$MINIO_ALIAS/$MINIO_BUCKET/$OUT_PATH-latest"

when:
  event:
    - push
    - manual
    - cron
