kind: pipeline
type: docker
name: build-so-upload

steps:
  - name: setup-go
    image: golang:1.23
    commands:
      - go version
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
      - apt-get update && apt-get install -y --no-install-recommends unzip ca-certificates curl git build-essential && rm -rf /var/lib/apt/lists/*
      - |
        if ! command -v protoc >/dev/null 2>&1; then
          PROTOC_VERSION="${PROTOC_VERSION:-24.4}"
          echo "Using PROTOC_VERSION=$PROTOC_VERSION"
          echo "Downloading: https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-linux-x86_64.zip"
          curl -sSL -o /tmp/protoc.zip "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-linux-x86_64.zip"
          unzip -o /tmp/protoc.zip -d /usr/local >/dev/null
          rm -f /tmp/protoc.zip
        fi
        export PATH="$PATH:/go/bin"
        /usr/local/bin/protoc -I=./proto --go_out=./sim/core ./proto/*.proto

  - name: build-shared-lib
    image: golang:1.23
    environment:
      CGO_ENABLED: 1
    commands:
      - go mod download
      - go build -buildmode=c-shared -o wowsimmop.so --tags=with_db ./sim/lib

  - name: upload-to-minio
    image: minio/mc
    environment:
      MINIO_ALIAS: minio
      MINIO_URL:
        from_secret: minio_url
      MINIO_ACCESS_KEY:
        from_secret: minio_access_key
      MINIO_SECRET_KEY:
        from_secret: minio_secret_key
      MINIO_BUCKET: artifacts
      OUT_PATH: lib/wowsimmop
    commands:
      - mc alias set "$MINIO_ALIAS" "$MINIO_URL" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
      - mc mb -p "$MINIO_ALIAS/$MINIO_BUCKET" || true
      - mc cp --attr "version=${CI_COMMIT_SHA}" wowsimmop.so "$MINIO_ALIAS/$MINIO_BUCKET/$OUT_PATH-${CI_COMMIT_SHA}"
      - mc cp wowsimmop.so "$MINIO_ALIAS/$MINIO_BUCKET/$OUT_PATH.so-latest"
      - mc cp wowsimmop.h "$MINIO_ALIAS/$MINIO_BUCKET/$OUT_PATH.h-latest"

when:
  event:
    - push
    - manual
    - cron
