kind: pipeline
type: docker
name: docker-build-and-push

# Note: Woodpecker cron schedules are created in the server/UI.
# Create a cron named "six-hourly-15" with schedule: 15 */6 * * *
# This pipeline is filtered to run only for that cron event.

steps:
  - name: docker-build-push
    image: plugins/kaniko
    settings:
      # Local, insecure registry
      registry: ${REGISTRY:-registry:5000}
      repo: ${REGISTRY:-registry:5000}/${IMAGE_NAME:-mop}
      dockerfile: Dockerfile
      context: .
      # Allow pushing to HTTP registry and skip TLS if any
      insecure: true
      skip_tls_verify: true
      # Tags: latest and full commit SHA
      tags:
        - latest
        - ${CI_COMMIT_SHA}
    when:
      event:
        - cron
        - push
        - manual
      cron:
        - six-hourly-15
