kind: pipeline
type: docker
name: docker-build-and-push

steps:
  - name: validate-secrets
    image: alpine:3.19
    environment:
      REGISTRY_URL:
        from_secret: registry_url
      REGISTRY_REPO:
        from_secret: registry_repo
      REGISTRY_USERNAME:
        from_secret: registry_username
      REGISTRY_PASSWORD:
        from_secret: registry_password
    commands:
      - echo "REGISTRY_URL=$REGISTRY_URL"
      - echo "REGISTRY_REPO=$REGISTRY_REPO"
      - echo "REGISTRY_USERNAME=$REGISTRY_USERNAME"
      - echo "REGISTRY_PASSWORD=$REGISTRY_PASSWORD"
      - '[ -n "$REGISTRY_URL" ] || { echo "Missing REGISTRY_URL"; exit 1; }'
      - '[ -n "$REGISTRY_REPO" ] || { echo "Missing REGISTRY_REPO"; exit 1; }'
      - '[ -n "$REGISTRY_USERNAME" ] || { echo "Missing REGISTRY_USERNAME"; exit 1; }'
      - '[ -n "$REGISTRY_PASSWORD" ] || { echo "Missing REGISTRY_PASSWORD"; exit 1; }'

  - name: docker-build-push
    image: woodpeckerci/plugin-kaniko
    settings:
      registry:
        from_secret: registry_url
      repo:
        from_secret: registry_repo
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - ${CI_COMMIT_SHA}
when:
  event:
    - cron
    - push
    - manual
