kind: pipeline
type: docker
name: docker-build-and-push

steps:
  - name: docker-build-push
    image: plugins/kaniko
    settings:
      registry:
        from_secret: registry_url
      repo: mop
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: Dockerfile
      context: .
      tags:
        - latest
        - ${CI_COMMIT_SHA}
    when:
      event:
        - cron
        - push
        - manual
      cron:
        - six-hourly-15
